### PR TITLE
151 landing page

### PR DESCRIPTION
**Pull request by lanaFerrari**

### CODE REVIEW

**Review by mattser — CHANGES_REQUESTED** [review]
This breaks React Routing. Components disappear on refresh. Has to be re-worked

**Comment by is-Lew** [comment]
Background does not display properly on larger screens. There is a few cm of whitespace on the right-hand side, would be worth addressing this

**Comment by lanaFerrari** [comment]
Can you check if it's fixed? I tried to target the outside div, so it should have done something. But on my screen was always fine so I'm gonna need some help here =) @happikaur @is-Lew

**Comment by lanaFerrari** [comment]
> This breaks React Routing. Components disappear on refresh. Has to be re-worked

Done

**Review by happikaur — CHANGES_REQUESTED** [review]
The tests are missing

**Review by happikaur — COMMENTED** [review]
The link in navbar needs to be removed. 
And the signed up button on footer needs to re-route to wallet for now.
Both would be changed in branch 177.

Tests need to be written for landing page

**Comment by lanaFerrari** [comment]
Added testing files, but also had to make some changes so the tests were completed. Removed the links and rerouted the button.

**Comment by lanaFerrari** [comment]
> The tests are missing

Done!

**Review by Harvir98 — APPROVED** [review]

**Review by happikaur — APPROVED** [review]
Navbar looks good with changes
Signup button takes you to wallet for now.

**Pull request merged**
